In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
np.random.seed(0)

n = 1000 # number of customers
df = pd.DataFrame({
    'CustomerID' : range(1, n+1),
    'Tenure' : np.random.randint(1, 60, n),
    'MontlyCharges' : np.random.uniform(20, 100, n),
    "SupportCalls": np.random.randint(0, 10, n),
    "LoginDays": np.random.randint(0, 30, n),
    "SatisfactionScore": np.random.randint(1, 6, n),
    "Complaints": np.random.randint(0, 5, n),
    "Churn": np.random.choice(
        ["Yes", "No"],
        size=n,
        p=[0.22, 0.78]
    )

})
df.head(10)

,CustomerID,Tenure,MontlyCharges,SupportCalls,LoginDays,SatisfactionScore,Complaints,Churn
0,1,45,36.779996,5,1,3,2,No
1,2,48,29.256259,9,21,1,4,No
2,3,54,66.171220,0,2,3,0,No
3,4,1,75.621600,8,1,2,1,No
4,5,4,73.756571,1,29,1,2,No
5,6,4,95.908882,6,13,2,0,No
6,7,40,20.216257,9,2,4,2,No
7,8,10,71.775732,7,14,3,3,No
8,9,20,68.031379,1,10,1,0,No
9,10,22,67.099169,4,9,2,1,No

In [8]:
# customer churn rate ---> lagging KPI
churn_rate = (df['Churn'] == 'Yes').mean() * 100
print(f"Customer Churn rate: {churn_rate:.2f}%")

# Average satisfaction score ---> Leading KPI
avg_satisfaction_score = df['SatisfactionScore'].mean()
print(f"Average Satisfaction Score: {avg_satisfaction_score:.2f}")

# Average Monthly charges ---> Leading KPI
avg_monthly_charges = df['MontlyCharges'].mean()
print(f"Average Monthly charges: {avg_monthly_charges:.2f}")

# Average SupportCalls ---> Leading KPI
avg_calls = df['SupportCalls'].mean()
print(f"Average Support Calls: {avg_calls:.2f}")

# Average LoginDays ---> Leading KPI
avg_login_days = df['LoginDays'].mean()
print(f"Average Login Days: {avg_login_days:.2f}")

# total Complaints ---> Leading KPI
total_complaints = df['Complaints'].sum()
print(f"Total complaints recieved: {total_complaints:.2f}")

Customer Churn rate: 21.80%
Average Satisfaction Score: 2.96
Average Monthly charges: 60.67
Average Support Calls: 4.51
Average Login Days: 14.09
Total complaints recieved: 1975.00

In [10]:
kpi_dashboard = pd.DataFrame({
    "KPI" : [
        "Churn Rate",
        "Average Satisfaction Score",
        "Average Monthly Charges",
        "Average Support Calls",
        "Average Login Days",
        "Total Complaints"
    ], 
    "Values" : [
        f"{churn_rate:.2f}%",
        round(avg_satisfaction_score, 2),
        f"${avg_monthly_charges:.2f}",
        round(avg_calls, 2),
        round(avg_login_days, 2),
        total_complaints
    ]
})

print(kpi_dashboard)

                          KPI  Values
0                  Churn Rate  21.80%
1  Average Satisfaction Score    2.96
2     Average Monthly Charges  $60.67
3       Average Support Calls    4.51
4          Average Login Days   14.09
5            Total Complaints    1975

In [13]:
target = {
    "Churn Rate" : 15, 
    "Average Satisfaction" : 3.2,
    "Average Monthly charges" : 70,
    "Average Calls" : 3,
    "Average Login Days" : 18,
    "Total complaints" : 1200
}
print(target)

print(f"Churn Rate          : {churn_rate:.2f}% (Target < {target['Churn Rate']}%)")
print(f"Satisfaction Score  : {avg_satisfaction_score:.2f} (Target > {target['Average Satisfaction']})")
print(f"Support Calls       : {avg_calls:.2f} (Target < {target['Average Calls']})")
print(f"Login Days          : {avg_login_days:.2f} (Target > {target['Average Login Days']})")

{'Churn Rate': 15, 'Average Satisfaction': 3.2, 'Average Monthly charges': 70, 'Average Calls': 3, 'Average Login Days': 18, 'Total complaints': 1200}
Churn Rate          : 21.80% (Target < 15%)
Satisfaction Score  : 2.96 (Target > 3.2)
Support Calls       : 4.51 (Target < 3)
Login Days          : 14.09 (Target > 18)

In [ ]:
high_risk = df[
    (df["SatisfactionScore"] <= 2) &
    (df["SupportCalls"] >= 5) &
    (df["LoginDays"] < 10)
]

print("High Risk Customers")


print(f"\nTotal High Risk Customers: {len(high_risk)}")

High Risk Customers

Total High Risk Customers: 73

In [16]:
high_risk.head()

,CustomerID,Tenure,MontlyCharges,SupportCalls,LoginDays,SatisfactionScore,Complaints,Churn
3,4,1,75.621600,8,1,2,1,No
12,13,24,75.718594,6,7,2,4,No
21,22,24,27.270859,8,5,1,2,No
25,26,38,90.956862,9,8,1,1,No
27,28,14,30.676918,6,9,1,3,No